### ISSUE TITLE
How can master file automatically copied into this depository?

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/projectjaraid.github.io#2]
@tillgrallert do you have any idea how would it be possible that the master TEI XML file would be copied automatically to this depository? So ProjectJaraid/jaraid_source/tei/jaraid_master.TEIP5.xml to here?
It is not a big deal to copy paste but it would more elegant if whenever we update the TEI master file in that repository (and we should keep it separate from the website materials where only a copy should be kept) Github would create a copy automatically here in this repository.
Any idea? Thank you!

**Comment by tillgrallert** [comment]
I suggest the following:

Do not copy but load the master file directly from the source repository. You would only need to create a gh-pages branch on jaraid_source and push any changes of content you want to see on the website to this branch. The master file can then be loaded with Ceteicean from https://projectjaraid.github.io/jaraid_source/tei/jaraid_master.TEIP5.xml

**Comment by Mestyan** [comment]
@tillgrallert thanks I will experiment. I believe that loading from an external source file may slow down the loading of the site but I investigate and will be back

**Comment by Mestyan** [comment]
@tillgrallert just a note that there is already a gh-pages in Jaraid source (https://github.com/ProjectJaraid/jaraid_source/tree/gh-pages) may I update it?

**Comment by tillgrallert** [comment]
@Mestyan sure. I just deleted the old `gh-pages` branch and created a new one as a copy of the current `master` branch

**Comment by Mestyan** [comment]
OK thanks

**Comment by Mestyan** [comment]
I did link in the jaraid_source file and it works perfectly. However, the update on the gh-page branch must be merged first to the master and only then it is displayed. I.e. the link https://projectjaraid.github.io/jaraid_source/tei/jaraid_master.TEIP5.xml is the master file itself and not the gh-pages branch. 
@tillgrallert  I just note this because I could equally continue on my "adam" branch simply and merge when I want to see the changes...what do you think? (I just want to reduce branches to avoid confusion)

**Comment by Mestyan** [comment]
@tillgrallert  nevermind, I tried again and yes, the link is the gh-pages branch!! it just needs a few mins to update itself . FASCINATING!!
