### ISSUE TITLE
automatization?

### ISSUE THREAD

**Issue by Mestyan** [ProjectJaraid/projectjaraid.github.io#5]
Dear @tillgrallert did you already do some tweaking with automatization through the VM? I see the JS codes stopped to work on the website. Let me know please! Many thanks! Btw, also, if the mutual xml update also works between master and authority files, soon I would start the cleaning of persNames because I think I am done with a large chunk of the titles. Best!

**Comment by tillgrallert** [comment]
I did reply via email at some point but wanted to quickly document the current state of work on automatization: A first Github action is up and running which propagates all changes from the authority file to the master file. The action to pre-process the maste file by converting it to HTML in order to speed up the rendering of the website will come in the next days.

**Comment by Mestyan** [comment]
thank you for this amazing work

**Comment by tillgrallert** [comment]
Dear Adam,
I just added the missing action to preprocess the TEI master file for publication with CETEIcean. The action is triggered by any change to the master file and generates the HTML file "jaraid_master.TEIP5.html" in the folder `html/`. You would now need to point your CETEIcean magic to this HTML file as the input instead of the old XML file. 

I have not yet added a sorting function for the table to the XSLT transformation. But I can do so and it would speed up rendering significantly. Let me know if I should do so.

**Comment by Mestyan** [comment]
Dear Till,

Fantastic! As far as I see the old XML file path still works (as it should as the xml file is still there in Github) - let me do quickly the pointing.

If I understand correctly what you say, already within this action you can in-built a sorting JavaScript? That would be fantastic! I know you may have more sophisticated solutions but feel free to use the sortTableChronologically JS among the website files.

Thank you!

Best wishes,
Adam

**Comment by Mestyan** [comment]
Sorry, I do not see an html folder on GitHub - where is it supposed to be? Or is it a virtual one?
So the path would be https://projectjaraid.github.io/html/jaraid_master.TEIP5.html <https://projectjaraid.github.io/html/jaraid_master.TEIP5.html> ?

**Comment by tillgrallert** [comment]
hi Adam, the folder is in the jaraid_source repository

**Comment by tillgrallert** [comment]
﻿
hi Adam, the folder is in the jaraid_source repository

**Comment by Mestyan** [comment]
I cannot see it anywhere there - ?

**Comment by tillgrallert** [comment]
ahhh. my bad. the action hasn’t run yet and therefore the html hasn’t been created

**Comment by Mestyan** [comment]
Should I run it?

**Comment by tillgrallert** [comment]
sure. why not :-)

**Comment by Mestyan** [comment]
I did change the master file, committed and pushed, but nothing happens?

**Comment by tillgrallert** [comment]
I will investigate. The action was triggered and completed. However, the output was not saved. odd

**Comment by tillgrallert** [comment]
locally the transformation works just fine and I manually added the HTML file. Still investigating the reasons for the action not saving the output

**Comment by Mestyan** [comment]
Perhaps an order for folder-creation?

**Comment by tillgrallert** [comment]
Found the culprit: the output path of the action has to be slightly different from locally run transformations. It should now work

**Comment by Mestyan** [comment]
It’s there! (Btw, I just praised you during a little conference in Paris)
I link in and report back

**Comment by tillgrallert** [comment]
Please note that I have added a function to sort the table to the XSLT the sort order is as follows:

- cell[@n = '1']/date/@when
- cell[@n = '1']/date/@notAfter
- cell[@n = '4']/name
- cell[@n = '4']/title

This means that you will not need to apply your JS sorting to the HTML for CETEIcean

**Comment by tillgrallert** [comment]
A note on actions: I am not sure if we have an unlimited number of action runs. As this is computing power on Github servers, they will almost certainly put a limit to free actions (academic accounts might be different though). With the current set-up every change to the authority file will trigger the action to update the master file, which, in turn, will trigger the action to update the HTML source for the website. Both actions spin up a virtual machine, install some software (involving downloads of 1+ GB in each case), and run the XSLT transformations. Each will take about 1,5 to 2 minutes to complete. This means that we should probably not immediately push every change to the authority file.

**Comment by Mestyan** [comment]
I think we should have a meeting to discuss the workflow etc. I send an email.

**Comment by Mestyan** [comment]
gracefully accomplished by @tillgrallert and @hcayless - thank you!!
